Generates a scala compiler bug:
java.lang.Error: ch.epfl.lamp.fjbg.JCode: offset too big to fit in 16 bits: 85542
at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:114)
at ch.epfl.lamp.fjbg.JClass.writeTo(JClass.java:315)
at scala.tools.nsc.backend.jvm.GenJVM.emitClass(GenJVM.scala:141)
at scala.tools.nsc.backend.jvm.GenJVM.genClass(GenJVM.scala:262)
at scala.tools.nsc.backend.jvm.GenJVM.apply(GenJVM.scala:56)
at scala.tools.nsc.backend.jvm.GenJVM2038anonfun.apply(GenJVM.scala:52)
at scala.tools.nsc.backend.jvm.GenJVM2038anonfun.apply(GenJVM.scala:52)
at scala.collection.mutable.HashMap2038anon2038anonfun.apply(HashMap.scala:89)
at scala.collection.mutable.HashMap2038anon2038anonfun.apply(HashMap.scala:89)
at scala.collection.Iterator.foreach(Iterator.scala:631)
at scala.collection.mutable.HashTable2038anon.foreach(HashTable.scala:161)
at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:194)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
at scala.collection.mutable.HashMap2038anon.foreach(HashMap.scala:89)
at scala.tools.nsc.backend.jvm.GenJVM.run(GenJVM.scala:52)
at scala.tools.nsc.Global.compileSources(Global.scala:741)
at scala.tools.nsc.Global.compile(Global.scala:822)
at xsbt.CompilerInterface.run(CompilerInterface.scala:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at xsbt.AnalyzingCompiler.call(AnalyzingCompiler.scala:40)
at xsbt.AnalyzingCompiler.apply(AnalyzingCompiler.scala:18)
at sbt.Compile.processScala(Compile.scala:76)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:27)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:27)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:22)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:22)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:45)
at sbt.CompilerCore2038anonfun.apply(Compile.scala:42)
at scala.Option.orElse(Option.scala:102)
at sbt.CompilerCore.doCompile(Compile.scala:41)
at sbt.CompilerCore.apply(Compile.scala:29)
at sbt.AbstractCompileConditional.run(Conditional.scala:341)
at sbt.AbstractCompileConditional2038anonfun.apply(Conditional.scala:344)
at sbt.AbstractCompileConditional2038anonfun.apply(Conditional.scala:344)
at sbt.classfile.Analyze$.apply(Analyze.scala:110)
at sbt.AbstractCompileConditional.execute(Conditional.scala:344)
at sbt.Conditional.run(Conditional.scala:43)
at sbt.AbstractCompileConditional.run(Conditional.scala:231)
at sbt.BasicScalaProject.sbt2038doCompile(DefaultProject.scala:260)
at sbt.BasicScalaProject2038anonfun.apply(DefaultProject.scala:274)
at sbt.BasicScalaProject2038anonfun.apply(DefaultProject.scala:274)
at sbt.TaskManager.invoke(TaskManager.scala:62)
at sbt.impl.RunTask.doRun(RunTask.scala:77)
at sbt.impl.RunTask.runTask(RunTask.scala:85)
at sbt.impl.RunTask.run(RunTask.scala:32)
at sbt.impl.RunTask$.apply(RunTask.scala:17)
at sbt.impl.RunTask$.apply(RunTask.scala:16)
at sbt.Project.run(Project.scala:98)
at sbt.Project.act(Project.scala:129)
at sbt.BasicScalaProject.act(DefaultProject.scala:21)
at sbt.xMain2038anonfun.apply(Main.scala:530)
at sbt.xMain2038anonfun.apply(Main.scala:530)
at sbt.xMain.withAction(Main.scala:563)
at sbt.xMain.sbt2038handleAction(Main.scala:530)
at sbt.xMain.handleCommand(Main.scala:520)
at sbt.xMain.processAction(Main.scala:459)
at sbt.xMain.process(Main.scala:257)
at sbt.xMain.processArguments(Main.scala:266)
at sbt.xMain.startProject(Main.scala:107)
at sbt.xMain.run(Main.scala:84)
at sbt.xMain.run0(Main.scala:35)
at sbt.xMain.run(Main.scala:42)
at xsbt.boot.Launch$.run(Launch.scala:53)
at xsbt.boot.Launch2038anonfun.apply(Launch.scala:42)
at xsbt.boot.Launch2038anonfun.apply(Launch.scala:42)
at xsbt.boot.Launch$.launch(Launch.scala:57)
at xsbt.boot.Launch$.explicit(Launch.scala:42)
at xsbt.boot.Launch$.initialized(Launch.scala:38)
at xsbt.boot.Launch$.parsed(Launch.scala:31)
at xsbt.boot.Launch$.configured(Launch.scala:21)
at xsbt.boot.Launch$.apply(Launch.scala:16)
at xsbt.boot.Launch$.apply(Launch.scala:13)
at xsbt.boot.Boot$.runImpl(Boot.scala:24)
at xsbt.boot.Boot$.run(Boot.scala:19)
at xsbt.boot.Boot$.main(Boot.scala:15)
at xsbt.boot.Boot.main(Boot.scala)
Caused by: ch.epfl.lamp.fjbg.JCode: offset too big to fit in 16 bits: 85542
at ch.epfl.lamp.fjbg.JCode.checkOffset16(JCode.java:896)
at ch.epfl.lamp.fjbg.JCode.patchAllOffset(JCode.java:975)
at ch.epfl.lamp.fjbg.JCode.freeze(JCode.java:95)
at ch.epfl.lamp.fjbg.JMethod.freeze(JMethod.java:81)
at ch.epfl.lamp.fjbg.JFieldOrMethod.writeTo(JFieldOrMethod.java:111)
... 78 more
Error during sbt execution: java.lang.Error: ch.epfl.lamp.fjbg.JCode: offset too big to fit in 16 bits: 85542